# Basic Setting
name: rafay_portfolio
description: "Portfolio Website for Abdul Rafay"
publish_to: "none"
version: 2.0.1+1
environment:
  sdk: ">=3.2.5 <4.0.0"

# Application Dependencies
dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.1.0
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  url_strategy: ^0.2.0
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.7.0
  crystal_navigation_bar: ^1.0.0
  web_smooth_scroll: ^1.1.0
  flutter_svg: ^2.0.9
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.15.5
  html_editor_enhanced: ^2.5.1
  firebase_storage: ^11.6.7
  image_picker: ^1.0.7
  path: ^1.8.3
  firebase_analytics: ^10.8.9
  image_picker_web: ^3.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_animation_progress_bar: ^2.3.1
  firebase_crashlytics: ^3.4.19
  timeline_tile: ^2.0.0
  showcaseview: ^2.0.3
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  scroll_to_index: ^3.0.1
  cached_network_image: ^3.3.1
  rxdart: ^0.27.7
  flutter_markdown: ^0.7.1
  flutter_staggered_grid_view: ^0.7.0
  open_file: ^3.3.2
  universal_html: ^2.2.4
  path_provider: ^2.1.2
  dio: ^5.4.2
  html_parser_plus: ^0.1.4
  highlight: ^0.7.0
  share: ^2.0.4
  share_plus: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter Design and Assets
flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/image/
    - assets/pdf/

# App Icons for application
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/favicon.png"
  web:
    generate: true
    image_path: "assets/image/favicon.png"
    background_color: "#FFF4F4"
    theme_color: "#31A499"
# Flutter Fonts
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
